---
sudo: false
language: ruby
rvm:
  - 1.9
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
script: bundle exec rake $TASK
env:
  - TASK=spec
matrix:
  include:
    env: TASK=rubocop
    rvm: 2.4
bundler_args: --without=localdev
